### ISSUE TITLE
Ubuntu 18.04.2 LTS no longer use ifupdown

### ISSUE THREAD

**Issue by TekunoKage** [tacacsgui/tgui_install#1]
root@tacacs-01:~/tgui_install# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@tacacs-01:~/tgui_install# more /etc/network/interfaces
\# ifupdown has been replaced by netplan(5) on this system.  See
\# /etc/netplan for current configuration.
\# To re-enable ifupdown on this system, you can run:
\#    sudo apt install ifupdown

That affect interfaces.sh scripts

**Comment by gurkin33** [comment]
Hello,

all discussion will be here https://github.com/tacacsgui/tgui_install/issues/2

Regards, Aleksey
