### ISSUE TITLE
What are the Ubuntu versions supported?

### ISSUE THREAD

**Issue by prtomasi** [tacacsgui/tgui_install#10]
Hi,

I'm confused.

Requirements say:

1. Clear Ubuntu 18.04.x (you can download iso here)

 - - - 

Step 2. Install Dependencies say:

11. Check Ubuntu version. Unfornunately, only 16.04.x supported.

- - - 

What is the recommend Ubuntu version to install tacacsgui?

Thanks!

**Comment by gurkin33** [comment]
Hello, 
It is compatible with Ubuntu 18.04.x only.
