### ISSUE TITLE
Error - Slim Framework not installed!!!

### ISSUE THREAD

**Issue by prtomasi** [tacacsgui/tgui_install#11]
Hi,

I tried to install tacacsgui on Ubuntu 18.04.5 LTS.

First it showed me an error about PHP:

###########    Error!    ###########
Error! PHP 7.3 Not Installed!
####################################

After use the commands below, PHP 7.3 was installed successfully

```
sudo apt-get install software-properties-common

sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
```

- - - 

Now I'm stuck on this error:

###########    Error!    ###########
Slim Framework not installed!!!
####################################

This way, frontend don't load correctly:
403 Forbidden - You don't have permission to access this resource.

Is there a way to install Slim Framework automatically?

Thanks!

**Comment by prtomasi** [comment]
After install from ISO everything worked!

https://tacacsgui.com/download/

Install from ISO, while installation set correct static IP (if you don’t use DHCP) with Internet access. After Installation use credentials tacgui/tacgui and execute command sudo /home/tacgui/tgui_install/tacacsgui.sh silent. And full installation will completed in few minutes, without any questions.

**Comment by Bikash-sah** [comment]
Me too

**Comment by Bikash-sah** [comment]
Hi,

Can you help on below error or share the command to recover it?

########### Error! ###########
Error! PHP 7.3 Not Installed!
####################################

########### Error! ###########
Slim Framework not installed!!!
####################################
