### ISSUE TITLE
Installation on Debian 10

### ISSUE THREAD

**Issue by MatthewKahle** [tacacsgui/tgui_install#12]
Hey gurkin33,

I just want to let you know, this a great project and I've used your appliance in my home lab here and there! I know your documentation says Ubuntu only at the moment, but I was wondering what the possibility would be to get this on Debian since Ubuntu is based off of Debian. I've started installing your appliance with some modifications to a Debian VM, I've had to manually add Ubuntu package keys and some repositories. So far I've gotten the web page running but I cannot authenticate with the first time user to finish the MYSQL deployment. 

Overall I was just wondering what tied this into being a Ubuntu appliance only. I prefer to use Debian in my home lab since it hasnt given me issues unlike Ubuntu..

Kind Regards,
--
Matthew

**Comment by gurkin33** [comment]
Dear Matthew,

Sorry, but it supports only Ubuntu, if you want install it under another linux distro, you should debug it by your own. Sorry one more time.

Regards, Aleksey

**Comment by MatthewKahle** [comment]
Hey Aleksey,

No problem, I just thought I would ask if you were using something
proprietary for Ubuntu.
As I mentioned, ive been working on getting this working for Debian, and if
I can get it to successfully work, I'll pass the details along if you're
interested.

Best Regards,
--
Matthew

**Comment by ElBigThor** [comment]
Hi Matthew,

I am also a Debian user, have you had any success?

Best regards,
--
Victor

**Comment by MatthewKahle** [comment]
Hey Victor,

I gave up a long time ago, a lot of packages broke...
I could try again with Debian-11, if you want to try to get this to work,
let's work together on it if you want.

Kind regards,
--
Matthew Kahle
