### ISSUE TITLE
Interfaces with @ on the name

### ISSUE THREAD

**Issue by TekunoKage** [tacacsgui/tgui_install#2]
On my current Hypervisor (Proxmox 5.4-3) environment for a lxc container the links inside the container look like:

root@tacacs-01:~/tgui_install# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
27: eth0@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0e:e7:47:58:e4:ab brd ff:ff:ff:ff:ff:ff link-netnsid 0

The use of @ on the link name affect the name detection on the func_if.sh I was able to modify the "function interface_list" to be able to properly display the interfaces, but still have issues with "function interface_existance"

###############################################################
###############################################################

ver. 1.0.0

##############     List of available options    ##############

1) Show Interface List      4) Clear and Refresh Menu
2) Show Interface Settings  5) Back to Main Menu
3) Configure interface

Please enter your choice (4 to clear output): 3

Type the name of interface: 
###########    Error!    ###########
Unrecognized Interface 
####################################

Please enter your choice (4 to clear output): 1

### Show Interface List ###

lo
eth0@if28

Please enter your choice (4 to clear output): 3

Type the name of interface: eth0@if28
###########    Error!    ###########
Unrecognized Interface eth0@if28
####################################

Please enter your choice (4 to clear output): ^C

Fix for:
function interface_list () {
  ip link | grep -Po '(?<=[0-9]: )[a-z0-9@]+(?=:)' | sed "s/^/${TABSPACE}/";
}

Any hint who to fix the rest of the functions?

**Comment by gurkin33** [comment]
Hello,

My bad. I changed the installation instruction, please do next thing:

## Prepare and run your script
- Move to home, delete old data (if it is) and download latest release (or just copy/past):

`cd ~; sudo rm -r tgui_install*; wget https://github.com/tacacsgui/tgui_install/archive/tgui_install.tar.gz`
- Unpack and move to unpacked files:

`mkdir tgui_install; tar -xvf tgui_install.tar.gz -C ~/tgui_install/ --strip-components 1; cd ./tgui_install`
- Make it executable and run:

`sudo chmod 755 ./tacacsgui.sh ; sudo ./tacacsgui.sh`
# OR
`sudo chmod 755 ./tacacsgui.sh ; sudo ./tacacsgui.sh silent`

**silent** run fast installation process.

I recommend finally use `sudo ./tacacsgui.sh silent`

Hope it will help.

Regards, Aleksey

**Comment by TekunoKage** [comment]
Thanks for your quick response. Now we are facing php installation problem on the automation. I attach some log... 

[Silent.log](https://github.com/tacacsgui/tgui_install/files/3095657/Silent.log)

I add lines below and bypass that message:

apt install software-properties-common
add-apt-repository ppa:ondrej/php

Regards,

**Comment by gurkin33** [comment]
Hello,

You can try to install it manually:

```
sudo apt-get install -y php7.3 php7.3-common php7.3-cli php7.3-fpm \
php7.3-curl php7.3-dev php7.3-gd php7.3-mbstring \
php7.3-zip php7.3-mysql php7.3-xml libapache2-mod-php7.3 php7.3-ldap
```
```
sudo a2dismod php7.*; sudo a2enmod php7.3; sudo service apache2 restart
```

Hope it will help.

Regards, Aleksey

P.S.: Why did you choose that way of manual installation? I [prepare the ISO file](https://tacacsgui.com/download/), you can use it and just follow [the instruction](https://tacacsgui.com/documentation/installation/manual/).

**Comment by TekunoKage** [comment]
I'm using an LXC container running on lxc will be more lite than running on a VM, therefore the ISO and the OVA (even are greate) those not work for my environment (Few RAM).

**Comment by gurkin33** [comment]
Oh. Ok.

Script tries to check PHP version:
```
echo $(php -v | grep -oE "(PHP 7\.3|)" | wc -l | tr -d '[:space:]');
```
And the result is not 1 in your case.

**Comment by TekunoKage** [comment]
With the two lines:

apt install software-properties-common
add-apt-repository ppa:ondrej/php

php is no longer an issue.

I'm facing other... Do you prefer to keep it on this issue or I should open a new one. I attach the last log anyway.

Thanks again!

[Silent_3.log](https://github.com/tacacsgui/tgui_install/files/3095775/Silent_3.log)

**Comment by gurkin33** [comment]
Hello,

Better open new one. I offer you to add the title - "Composer issue, Slim Framework not installed"

Regards, Aleksey
