### ISSUE TITLE
Composer issue, Slim Framework not installed | Dependencies

### ISSUE THREAD

**Issue by TekunoKage** [tacacsgui/tgui_install#3]
Silent installation

###########    Error!    ###########
Slim Framework not installed!!!
####################################

[Silent_3.log](https://github.com/tacacsgui/tgui_install/files/3095867/Silent_3.log)

Thanks,

**Comment by gurkin33** [comment]
Hello,

Could you send me a result of next commands:
```
ll /opt/tacacsgui/web/api
cat /opt/tacacsgui/web/api/composer.json
sudo -u  www-data composer update -d /opt/tacacsgui/web/api
sudo -u  www-data composer install -d /opt/tacacsgui/web/api
```

Regards, Aleksey

**Comment by TekunoKage** [comment]
Inside /opt/tacacsgui/ there is no directory 'web'. Below the output

root@tacacs-naf1:~/tgui_install# ls /opt/tacacsgui -l 
total 4
-rw-rw-rw- 1 www-data www-data  0 Apr 18 18:34 tacTestOutput.txt
-rw-rw-rw- 1 www-data www-data 70 Apr 18 18:40 tac_plus.cfg
-rw-rw-rw- 1 www-data www-data  0 Apr 18 18:34 tac_plus.cfg_test

**Comment by gurkin33** [comment]
Hmm..
Could you try to clone repo:
```
sudo -u  www-data git -C /opt/tacacsgui clone https://github.com/tacacsgui/tacacsgui /opt/tacacsgui
```

Regards, Aleksey

**Comment by TekunoKage** [comment]
look like problems with git.
The git packages are not installed...

 root@tacacs-naf1:\~/tgui_install# sudo -u  www-data git -C /opt/tacacsgui clone https://github.com/tacacsgui/tacacsgui /opt/tacacsgui
sudo: git: command not found
root@tacacs-naf1:~/tgui_install# apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn
The following NEW packages will be installed:
  git git-man liberror-perl
0 upgraded, 3 newly installed, 0 to remove and 6 not upgraded.
Need to get 4733 kB of archives.
After this operation, 33.9 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.


I will install it manually and run the install again to check...

**Comment by gurkin33** [comment]
Looks like I should add it to the installation script.

Let me know a result.

Regards, Aleksey

**Comment by TekunoKage** [comment]
> 
> 
> Looks like I should add it to the installation script.
> 
> Let me know a result.
> 
> Regards, Aleksey

After add git the the script start to execute, and look like complete, but I was not able to access the website. I check both protocols http and https.

https://<IP_Address>:4443
http://<IP_Address>:8008

Attach is the log file after install git
[Silent_4.log](https://github.com/tacacsgui/tgui_install/files/3096088/Silent_4.log)

**Comment by gurkin33** [comment]
How does it look? Nothing happens or you see "Loading..." screen?

Regards, Aleksey

**Comment by TekunoKage** [comment]
> s it look? Nothing happens or you see "Loading..." scre

Nothing... not even a error message on the browser...

I'm trying to find if there a request on the server side...

any tip?

**Comment by TekunoKage** [comment]
look like is not listen on IPv4 for the port 4443 and 8008:

```
root@tacacs-naf1:~# netstat -lt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:mysql         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:domain       0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp        0      0 localhost:smtp          0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:8008               [::]:*                  LISTEN     
tcp6       0      0 [::]:http               [::]:*                  LISTEN     
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 localhost:smtp          [::]:*                  LISTEN     
tcp6       0      0 [::]:4443               [::]:*                  LISTEN     
tcp6       0      0 [::]:https              [::]:*                  LISTEN 
```

**Comment by gurkin33** [comment]
May be we can find a clue inside of:
```
 tail -10 /var/log/tacacsgui/apache2/error.log 
```

P.S.: see you tomorrow 🌚

**Comment by TekunoKage** [comment]
> 
> 
> May be we can find a clue inside of:
> 
> ```
>  tail -10 /var/log/tacacsgui/apache2/error.log 
> ```
> 
> P.S.: see you tomorrow new_moon_with_face

Nothing just cert errors....

P.S.: Good weekend... Tomorrow is a Holiday here

**Comment by gurkin33** [comment]
Hello,

Any way, could you attached log from _/var/log/tacacsgui/apache2/error.log_?
And output from:
```
apache2ctl -S
service apache2 status
```

Regards, Aleksey

**Comment by TekunoKage** [comment]
> 
> 
> Hello,
> 
> Any way, could you attached log from _/var/log/tacacsgui/apache2/error.log_?
> And output from:
> 
> ```
> apache2ctl -S
> service apache2 status
> ```
> 

Hi again,
`root@tacacs-naf1:~# service apache2 status                                     
* apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: active (running) since Mon 2019-04-22 15:42:17 UTC; 13min ago
  Process: 161 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
 Main PID: 235 (apache2)
    Tasks: 6 (limit: 21601)
   CGroup: /system.slice/apache2.service
           |-235 /usr/sbin/apache2 -k start
           |-241 /usr/sbin/apache2 -k start
           |-242 /usr/sbin/apache2 -k start
           |-243 /usr/sbin/apache2 -k start
           |-244 /usr/sbin/apache2 -k start
           `-246 /usr/sbin/apache2 -k start

Apr 22 15:42:17 tacacs-naf1 systemd[1]: apache2.service: Failed to reset devices.list: Operation not permitted
Apr 22 15:42:17 tacacs-naf1 systemd[1]: Starting The Apache HTTP Server...
Apr 22 15:42:17 tacacs-naf1 apachectl[161]: /usr/sbin/apachectl: 99: ulimit: error setting limit (Operation not permitted)
Apr 22 15:42:17 tacacs-naf1 apachectl[161]: Setting ulimit failed. See README.Debian for more information.
Apr 22 15:42:17 tacacs-naf1 systemd[1]: Started The Apache HTTP Server.
root@tacacs-naf1:\~# apache2ctl -S                                              
/usr/sbin/apache2ctl: 99: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.
VirtualHost configuration:
*:80                   tacacs-naf1.local.net (/etc/apache2/sites-enabled/000-default.conf:1)
*:4443                 tacacsgui.local (/etc/apache2/sites-enabled/tacacsgui.local-ssl.conf:4)
*:8008                 tacacs-naf1.local.net (/etc/apache2/sites-enabled/tacacsgui.local.conf:3)
ServerRoot: "/etc/apache2"
Main DocumentRoot: "/var/www/html"
Main ErrorLog: "/var/log/apache2/error.log"
Mutex ssl-stapling: using_defaults
Mutex ssl-cache: using_defaults
Mutex default: dir="/var/run/apache2/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex watchdog-callback: using_defaults
Mutex rewrite-map: using_defaults
Mutex ssl-stapling-refresh: using_defaults
PidFile: "/var/run/apache2/apache2.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="www-data" id=33
Group: name="www-data" id=33
root@tacacs-naf1:~#`

[Apache2_error.log](https://github.com/tacacsgui/tgui_install/files/3103957/Apache2_error.log)

Thanks a lot Josiel,

**Comment by gurkin33** [comment]
Hello Josiel,

The line `tcp6       0      0 [::]:8008` is ok, it is normal, please, google it, if you want more info.

I think it is a network issue. Could you do next thing from your PC:
```
ping <server-ip-address>
telnet <server-ip-address> 8008
```
Regards, Aleksey

**Comment by TekunoKage** [comment]
> 
> I think it is a network issue. Could you do next thing from your PC:
> 
> ```
> ping <server-ip-address>
> telnet <server-ip-address> 8008
> ```
> 

Is not a reach ability issue because I'm able to ssh the server from my computer and also the Apache2 test page is working on the browser.

I also do on the same server an wget http://<ip_address>:8008 and that work downloading the index.html

When I do the telnet to the port 8008 I get no response, the same behavior than the web browser.

Output below confirm current connection as Established...

```
root@tacacs-naf1:~/test# netstat -anp --tcp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      224/mysqld          
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      137/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      199/sshd            
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      404/master          
tcp        0     96 <ip_address>:22        192.168.29.24:63794     ESTABLISHED 999/sshd: root@pts/ 
tcp6       0      0 :::8008                 :::*                    LISTEN      1635/apache2        
tcp6       0      0 :::80                   :::*                    LISTEN      1635/apache2        
tcp6       0      0 :::22                   :::*                    LISTEN      199/sshd            
tcp6       0      0 ::1:25                  :::*                    LISTEN      404/master          
tcp6       0      0 :::4443                 :::*                    LISTEN      1635/apache2        
tcp6       0      0 :::443                  :::*                    LISTEN      1635/apache2        
tcp6       0      0 <ip_address>:80        192.168.29.24:59784     ESTABLISHED 1638/apache2 
```

If you think this is a different issue than the open, maybe we can open another case to leave the solution for this one more clear 

Regards,

**Comment by TekunoKage** [comment]
I guest I figure out what is happening with the connection issue. I think is my firewall that is blocking http traffic that is not associated with port 80, even the rule state http. I will work on that and confirm it to you. 

Sorry about that last part...

Regards,

**Comment by TekunoKage** [comment]
Can you check other dependencies additional to git?

My server don't have python-pip installed and the script "install.sh" look like is using it on the line 267.

I notice we still have an issue because the webpage remain in loading forever.

P.S. I attach my server apt list filtering automatic, maybe that give you a hint of what could be missing.

Regards,

[Non_automatic Installed apps.txt](https://github.com/tacacsgui/tgui_install/files/3105052/Non_automatic.Installed.apps.txt)

**Comment by TekunoKage** [comment]
After manually install python-pip, the website move forward to prompt asking for username and password.

After that start to do additional checks and installs and finally get to the Dashboard. I guest that complete the install.

Thanks for all your support. 

Regards, 
Josiel

**Comment by gurkin33** [comment]
Hello Josiel,

Glad to hear that. Have a great day.

You can thank me, help the project and a developer via [Patreon](https://www.patreon.com/tacacsgui).
Best Regards, Aleksey
Developer of TacacsGUI

**Comment by TekunoKage** [comment]
After manually install python-pip, the website move forward to prompt asking for username and password.

After that start to do additional checks and installs and finally get to the Dashboard. I guest that complete the install.

Thanks for all your support. 

Regards, 
Josiel
