### ISSUE TITLE
MySQL root password

### ISSUE THREAD

**Issue by Seethaar** [tacacsgui/tgui_install#4]
With the help of old documentation, I installed tacacsgui
https://tacacsgui.com/documentation_old/install-tacacsgui/

At the step where it asks for root password for MySQL and I could not authenticate with any password here.

```
###############################################################
##############   TACACSGUI Installation    #########
###############################################################

ver. 1.0.0


Start Installation
Check database...
Try to get root password to MySQL...Not Found
Enter root password to mysql:
###########    Error!    ###########
Incorrect MYSQL root password! Exit.
####################################
```
just curious if there is a preset password or if it is asking for system root password.

**Comment by gurkin33** [comment]
Hello,
First of all I see that you use old version of installer.
Next question why did you try install it with old manual?
If you want to try to install it on clear Ubuntu try to use [that instruction](https://tacacsgui.com/documentation/installation/re-installation/).

Regards, Aleksey

**Comment by Seethaar** [comment]
Thanks mate. In the absence of new documentation, I got lead to the old one and hence I did the old way.

Just downloaded the ISO image and this install works fine.
Thanks,

**Comment by shkakhya** [comment]
I also encontered same error message. I was installing tacacsgui in clean ubuntu 18.04 on docker. I had to manually install php7.3 on it. I got the following error.

###############################################################
##############   TACACSGUI Installation    #########
###############################################################

ver. 2.0.0


Start Installation
Silent installation detected!
Check database...
Try to get root password to MySQL...Not Found
Try to get from fresh install...Enter root password to mysql: 
###########    Error!    ###########
Incorrect MYSQL root password! Exit.
####################################

Try one more time? (y/n): y

I was following the installation guide from https://tacacsgui.com/documentation/installation/manual/install-tacacsgui/
