### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by subu1979** [tacacsgui/tgui_install#7]
Hi 

After successful installation, what is the credentials to logon to the system

https://192.168.0.45:4443
http://192.168.0.45:8008

What is the default credentials for MYSQL ??

**Comment by gurkin33** [comment]
Hello,

**tacgui**/**tacgui**

Default credential to mysql inside /opt/tacacsgui/web/api/config.php

**Comment by subu1979** [comment]
Thanks for your response.
